_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 512
clip_range:
    value: 0.1
collapse_patience_limit:
    value: 20000
collapse_trial_length:
    value: 10000
collapse_warmup_limit:
    value: 500000
ent_coef:
    value: 0.01
env_name:
    value: ALE/MsPacman-v5
expanded_phi_band:
    value: 0.5
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
harmonic_epsilon:
    value: 0.1
kl_ema_alpha:
    value: 0.001
kl_stability_threshold:
    value: 0.005
learning_rate:
    value: 0.00025
n_envs:
    value: 8
n_steps:
    value: 256
project_name:
    value: miltronic-pacman-v5-stable-warmup
seed:
    value: 2028
stability_eval_warmup:
    value: 20
total_timesteps:
    value: 5000000
