_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 55
            "4": 3.8.10
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 512
clip_range:
    value: 0.1
env_name:
    value: ALE/MsPacman-v5
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
initial_ent_coef:
    value: 0.01
k_prime_ema_alpha:
    value: 0.01
learning_rate:
    value: 0.00025
mode:
    value: miltronic_k_prime
n_envs:
    value: 8
n_epochs:
    value: 4
n_steps:
    value: 256
policy_type:
    value: CnnPolicy
project_name:
    value: miltronic-k-prime-release
reward_shaping_lambda:
    value: 0.05
run_name:
    value: miltronic_k_prime_ALE/MsPacman-v5_seed_42
seed:
    value: 42
total_timesteps:
    value: 5000000
