_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "10":
                - 20
            "12": 0.20.1
            "13": linux-x86_64
agent_type:
    value: miltronic
batch_size:
    value: 256
clip_range:
    value: 0.1
ent_cap:
    value: 0.2
env_name:
    value: ALE/MsPacman-v5
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
k_scale_factor:
    value: 5
kl_div_threshold:
    value: 0.05
lambda_0:
    value: 0.05
n_envs:
    value: 8
n_epochs:
    value: 4
n_steps:
    value: 128
project_name:
    value: miltronic-pacman-v1-final
seed:
    value: 42
seeds:
    value:
        - 42
        - 123
        - 456
        - 789
        - 1011
sweep_lambdas:
    value:
        - 0.05
        - 0.1
        - 0.2
sweep_seed:
    value: 42
total_timesteps_full:
    value: 5000000
total_timesteps_sweep:
    value: 1000000
